version: "3.9"
services:
  aeong:
    image: mpasini/aeong:latest
    command:
      - /bin/bash
      - -c
      - |
        cd build
        ./memgraph
    ports:
      - 7687:7687
      - 7444:7444
    deploy:
      placement:
        constraints:
          - node.hostname == area40cl2