version: "3.9"
services:
  asterix_cc:
    image: mp4sini/asterixdb:latest
    ports:
      - 19006:19006
    # volumes:
    #   - namenode1_data:${NAMEDIR}
    #   - namenode1_config:${HADOOPCONFDIR}
    command:
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
  #        - node.labels.running_asterix_cc==0
    networks:
      - BIG-dataplatform-network 

  # asterix_nc1:
  #   image: mp4sini/asterixdb:latest
  #   ports:
  #     - ${NAMENODE1PORT}:${NAMENODE1PORT}
  #   volumes:
  #     - namenode1_data:${NAMEDIR}
  #     - namenode1_config:${HADOOPCONFDIR}
  #   command:
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager
  #         - node.hostname != CB-Mass-Node1
  #         - node.labels.running_asterix_cc==0
  #   networks:
  #     - BIG-dataplatform-network 

  # asterix_nc2:
  #   image: mp4sini/asterixdb:latest
  #   ports:
  #     - ${NAMENODE1PORT}:${NAMENODE1PORT}
  #   volumes:
  #     - namenode1_data:${NAMEDIR}
  #     - namenode1_config:${HADOOPCONFDIR}
  #   command:
  #   deploy:
  #     placement:
  #       constraints:
  #         - node.role == manager
  #         - node.hostname != CB-Mass-Node1
  #         - node.labels.running_asterix_cc==0
  #   networks:
  #     - BIG-dataplatform-network 


volumes:
  namenode1_config:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/
    
networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
