version: "3.9"
services:
  asterix_cc:
    image: mp4sini/asterixdb:latest
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
      - 19003:19003
      - 1009:1009
      - 1098:1098

    volumes:
      - /home/mpasini/asterix_conf_files:${CCCONFDIR}
    command:
      - /bin/bash
      - -c
      - |
        sleep 40
        bin/asterixcc -config-file cc.conf > cc.log 2>&1 &
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  asterix_nc1:
    image: mp4sini/asterixdb:latest
    ports:
      - 1099:1099
      - 9090:9090
    volumes:
      - /home/mpasini/asterix_conf_files:${CCCONFDIR}
    command: bin/asterixncservice > red-service.log 2>&1 &
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 

  asterix_nc2:
    image: mp4sini/asterixdb:latest
    ports:
      - 1099:1099
      - 9090:9090
    volumes:
      - /home/mpasini/asterix_conf_files:${CCCONFDIR}
    command: bin/asterixncservice > blue-service.log 2>&1 &
    deploy:
      placement:
        constraints:
          - node.role == manager
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network 


volumes:
  namenode1_config:
    driver_opts:
      type: nfs
      o: addr=${NFSADDRESS},rw,nfsvers=4
      device: :${NFSPATH}/
    
networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
