version: "3.9"
services:
  asterix_cc:
    image: mp4sini/asterixdb:latest
    ports:
      - 19006:19006

    volumes:
      - /home/mpasini/asterix_conf_files/:/workspace/asterixdb/asterixdb/asterix-server/target/asterix-server-0.9.10-SNAPSHOT-binary-assembly/apache-asterixdb-0.9.10-SNAPSHOT/opt/local/conf

    command:
        - /bin/bash
        - -c
        - |
          sleep 40
          bin/asterixcc -config-file /workspace/asterixdb/asterixdb/asterix-server/target/asterix-server-0.9.10-SNAPSHOT-binary-assembly/apache-asterixdb-0.9.10-SNAPSHOT/opt/local/conf/cc.conf > cc.log 2>&1 &
    deploy:
      placement:
        constraints:
          - node.hostname == area40cl2
    networks:
      - BIG-dataplatform-network


  asterix_nc1:
    image: mp4sini/asterixdb:latest
    command:
        - /bin/bash
        - -c
        - |
           bin/asterixncservice > red-service.log 2>&1 &
           tail -f red-service.log
    deploy:
      placement:
        constraints:
          - node.hostname == area40cl6
    networks:
      - BIG-dataplatform-network


  asterix_nc2:
    image: mp4sini/asterixdb:latest
    command:
        - /bin/bash
        - -c
        - |
           bin/asterixncservice > blue-service.log 2>&1 &
           tail -f blue-service.log
    deploy:
      placement:
        constraints:
          - node.hostname == area40cl3
    networks:
      - BIG-dataplatform-network

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
